<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>gemini-blueprint</artifactId>
        <groupId>org.eclipse.gemini.blueprint</groupId>
        <version>1.0.2.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.eclipse.gemini.blueprint</groupId>
    <artifactId>gemini-blueprint-extender</artifactId>
    <packaging>jar</packaging>
    <name>Gemini Blueprint Extender</name>
    <url>http://www.eclipse.org/gemini/blueprint/</url>

    <description>
        Eclipse Gemini Blueprint extender. Listens for and bootstraps OSGi 4.2 Blueprint and Spring-powered OSGi
        bundles.
    </description>

    <properties>
        <javadoc.loc>${basedir}/../docs/src/javadoc</javadoc.loc>
        <spring.osgi.symbolic.name>${symName.prefix}.extender</spring.osgi.symbolic.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.gemini.blueprint</groupId>
            <artifactId>gemini-blueprint-mock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.gemini.blueprint</groupId>
            <artifactId>gemini-blueprint-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.gemini.blueprint</groupId>
            <artifactId>gemini-blueprint-io</artifactId>
        </dependency>
        <dependency>
            <groupId>aopalliance</groupId>
            <artifactId>aopalliance</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
           	<artifactId>org.osgi.compendium</artifactId>
            <version>4.2.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Bundle-Activator>org.eclipse.gemini.blueprint.extender.internal.boot.ChainActivator</Bundle-Activator>
                        <Export-Package>
                            !*internal*,
                            *
                        </Export-Package>
                        <Import-Package>
                            org.eclipse.gemini.blueprint.extensions.annotation;resolution:=optional;version="${gemini.blueprint.version.range.nq}",
                            org.osgi.service.packageadmin;version="1.2",
                            org.osgi.service.blueprint.container;version="1.0.0";resolution:=optional,
                            org.osgi.service.blueprint.reflect;version="1.0.0";resolution:=optional,
                            org.osgi.framework;version="1.3",
                            org.aopalliance.*;version="0.0.0",
                            org.osgi.service.cm;version="1.2";resolution:=optional,
                            org.osgi.service.event;version="1.1";resolution:=optional,
                            org.osgi.util.tracker;version="1.3",
                            org.apache.commons.logging.*;version=${logging.version.range},
                            org.eclipse.gemini.blueprint.blueprint.*;version=${gemini.blueprint.version.range},
                            org.eclipse.gemini.blueprint.*;version=${gemini.blueprint.version.range},
                            org.springframework.*;version=${spring.version.range},
                            *;resolution:=optional
                        </Import-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
